apiVersion: v1
kind: Service
metadata:
  name: sdt-backend
spec:
  selector:
    app: sdt
    service: backend
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdt-backend
  labels:
    app: sdt
    service: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sdt
      service: backend
  template:
    metadata:
      labels:
        app: sdt
        service: backend
    spec:
      containers:
      - name: backend
        image: 5bondarenko/sdt-course-work-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sdt-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sdt-secret
              key: postgres-password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: sdt-configmap
              key: database-host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: sdt-configmap
              key: database-name