apiVersion: v1
kind: Service
metadata:
  name: sdt-frontend
spec:
  selector:
    app: sdt
    service: frontend
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdt-frontend
  labels:
    app: sdt
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdt
      service: frontend
  template:
    metadata:
      labels:
        app: sdt
        service: frontend
    spec:
      containers:
      - name: frontend
        image: TODO
        ports:
        - containerPort: 8080